version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: mvc_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mvc_network

  adminer:
    image: adminer:latest
    container_name: mvc_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - mvc_network

volumes:
  postgres_data:

networks:
  mvc_network:
    driver: bridge